# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Programs\not-virus\ui\Gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 215)
        Form.setMinimumSize(QtCore.QSize(400, 215))
        Form.setMaximumSize(QtCore.QSize(400, 215))
        self.Title = QtWidgets.QLabel(Form)
        self.Title.setGeometry(QtCore.QRect(10, 10, 380, 15))
        self.Title.setStyleSheet("color: rgb(218, 114, 24);")
        self.Title.setObjectName("Title")
        self.BuleScreen = QtWidgets.QPushButton(Form)
        self.BuleScreen.setGeometry(QtCore.QRect(15, 35, 100, 45))
        self.BuleScreen.setObjectName("BuleScreen")
        self.UEFI = QtWidgets.QPushButton(Form)
        self.UEFI.setGeometry(QtCore.QRect(120, 35, 100, 45))
        self.UEFI.setObjectName("UEFI")
        self.BlueScreenCode = QtWidgets.QLineEdit(Form)
        self.BlueScreenCode.setGeometry(QtCore.QRect(290, 36, 90, 20))
        self.BlueScreenCode.setObjectName("BlueScreenCode")
        self.BlueScreenCodeTip = QtWidgets.QLabel(Form)
        self.BlueScreenCodeTip.setGeometry(QtCore.QRect(225, 39, 60, 15))
        self.BlueScreenCodeTip.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.BlueScreenCodeTip.setObjectName("BlueScreenCodeTip")
        self.BIOSModeTip = QtWidgets.QLabel(Form)
        self.BIOSModeTip.setGeometry(QtCore.QRect(225, 60, 60, 16))
        self.BIOSModeTip.setObjectName("BIOSModeTip")
        self.BIOSMode = QtWidgets.QComboBox(Form)
        self.BIOSMode.setGeometry(QtCore.QRect(290, 58, 90, 20))
        self.BIOSMode.setObjectName("BIOSMode")
        self.Log = QtWidgets.QGroupBox(Form)
        self.Log.setGeometry(QtCore.QRect(15, 80, 370, 120))
        self.Log.setObjectName("Log")
        self.LogDisplay = QtWidgets.QTextBrowser(self.Log)
        self.LogDisplay.setGeometry(QtCore.QRect(5, 15, 360, 100))
        self.LogDisplay.setObjectName("LogDisplay")
        self.Tip = QtWidgets.QLabel(Form)
        self.Tip.setGeometry(QtCore.QRect(1, 201, 265, 11))
        self.Tip.setObjectName("Tip")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "通用UEFI-CEF注入器"))
        self.Title.setText(_translate("Form", "该程序正处于Dev开发版中，可能出现错误，注入前请备份系统及文件！"))
        self.BuleScreen.setText(_translate("Form", "蓝屏注入"))
        self.UEFI.setText(_translate("Form", "UEFI启动注入"))
        self.BlueScreenCodeTip.setText(_translate("Form", "蓝屏代码："))
        self.BIOSModeTip.setText(_translate("Form", "BIOS类型："))
        self.Log.setTitle(_translate("Form", "日志记录器"))
        self.Tip.setText(_translate("Form", "BIOS模式(自动检测)：UEFI BIOS  安全模式：否"))
