# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Programs\not-virus\ui\SetUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(395, 90)
        Form.setMinimumSize(QtCore.QSize(395, 90))
        Form.setMaximumSize(QtCore.QSize(395, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        Form.setFont(font)
        Form.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 30, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "通用UEFI-CEF注入器"))
        self.label.setText(_translate("Form", "加载文件..."))
